content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    filename: '{year}-{month}-{day}-{fields.title}.md'
    fields: 
      - name: title
        label: Title
        type: string
  - name: pages
    label: Pages
    path: Pages
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
  - name: articles
    label: Articles
    path: articles
    type: collection
    fields: 
      - name: title
        label: Title
        type: string