content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    filename: '{year}-{month}-{day}-{fields.title}.md'
    fields: 
      - name: title
        label: Title
        type: string
  - name: pages
    label: Pages
    path: pages
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
      - name: permalink
        label: permalink
        type: string
  - name: essays
    label: Essays
    path: essays
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
      - name: permalink
        label: permalink
        type: string