content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    fields: 
      - title
      - tags[0]
  - name: pages
    label: Pages
    path: Pages
    type: collection
    fields: 
    - title
  - name: articles
    lable: Articles
    path: articles
    type: collection
    fields: 
    - title